sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_4b3f489a095e_key -iv $encrypted_4b3f489a095e_iv -in multi-k8s-291416-304406f62b67.json.enc -out multi-k8s-291416-304406f62b67.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --keyfile multi-k8s-291416-304406f62b67.json